# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='e_mail',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='username',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='RUC',
            field=models.IntegerField(),
        ),
    ]
